### PR TITLE
Obj-C compatibility

### PR DESCRIPTION
**Pull request by hohteri**
Added @objc declarations to some properties and methods

### CODE REVIEW

**Comment by hohteri** [comment]
Sorry for opening and closing, it seems to merge from master so my last commit is included.

**Comment by luispadron** [comment]
Thanks for this, I'm not too familiar with Objective-C, but is `@objc` required for all members that need to be interopped with Objc? Is this also because of the new Swift 4 changes? 

Also, if that is the case, shouldn't we do `@objcMembers` instead?

I get this from https://useyourloaf.com/blog/objc-warnings-upgrading-to-swift-4/ 

This way any new properties/members will automatically work with Obj-C, without requiring `@objc` explicitly.

**Comment by hohteri** [comment]
Yes, Swift 4 requires @objc. I don’t know about @objcMembers I can try to check your link at later time. There is one method/property (can’t remember out of my head) with CGFloat? parameter which can’t be translated to objc as it doesn’t have nullable primitive types.

Harri

**Comment by luispadron** [comment]
Yes, I think that would be `currentValue`, which is really just a simple getter. I guess if we wanted that to be available in Obj-C, we would need to make it a function instead of a member? Thinking about it a bit more, I like the idea of explicitly saying `@objc` instead of the cascading `@objcMembers` as it requires the writer to be explicit about whether they want to make it available in ObjC.

If you have any ideas about how to get `currentValue` working in ObjC without breaking existing API's, or if you believe the use case is too small that some support but not full support is enough, then let me know.

Otherwise, if you've tested it in an ObjC project and such let me know so I can go ahead and merge it, thanks again for contributing!

**Comment by hohteri** [comment]
SO suggested replacing it with NSNumber but that would break existing API. I don’t know if changing it to CGFloat! breaks anything and if it can be null ever. 

I did use the setProgress method successfully in objc. That worked fine. I didn’t use the properties but don’t see why they wouldn’t work. I’m going to use the gradient properties in the near future. 

Finally I don’t know if the delegate works as I haven’t yet used it or if adding the default value of nil breaks something on swift side. 

I assumed the tests are run when building with Carthage but I’m not sure. And I didn’t look if the tests actually test all the properties and functionality on swift side. 

I’m looking for to provide an attributed string as a property for the label but haven’t yet got that far. 

Thank you for providing a good piece of functionality as open source.

**Comment by luispadron** [comment]
All tests passed, merging!

**Pull request merged**
