### PR TITLE
Adding more flexibility to knob styling with shadow properties

### PR DESCRIPTION
**Pull request by xismic**
as requested [here](https://github.com/luispadron/UICircularProgressRing/issues/112)

### CODE REVIEW

**Comment by luispadron** [comment]
Thanks for this, I’ll look at it after work!

**Comment by luispadron** [comment]
Looks great and thanks for updating the tests as well!

**Comment by luispadron** [comment]
Available now in [3.1.0](
https://github.com/luispadron/UICircularProgressRing/releases/tag/v3.1.0), thanks again!

**Comment by xismic** [comment]
Appreciate the quick turn around :)

**Pull request merged**
