### PR TITLE
Version 3.3.1

### PR DESCRIPTION
**Pull request by luispadron**
Adds changes for fixing continue/pause logic

### CODE REVIEW

**Comment by nickdnk** [comment]
Hello

Did you check this? I can't even compile it. It says all the helper methods are inaccessible because they're private. I think it's because you moved them into an extension. Something is definitely wrong with 3.3.1.

**Comment by luispadron** [comment]
That's weird? Yes, I compiled and ran an example project it also passed CI.
Are you trying to access the helper functions from within your own code?

**Comment by nickdnk** [comment]
No. It says from within UICircularProgressRing.swift that it cannot access `snapshottedAnimation`, in the helper extension and that `snapshotProgress`, `restoreProgress` and `animationDidComplete` are not accessible from `continueProgress` and `pauseProgress`. Is this related to some Swift versioning?

**Comment by luispadron** [comment]
Which swift version are you on?

**Comment by nickdnk** [comment]
3.3

**Comment by luispadron** [comment]
Oh yah, then I think you're really behind on the Swift version aspect of things. 

This project has always used the latest version of Swift, which as of Xcode 9.3 that is Swift 4.1. 
I believe in 4.0 they allowed the use of extensions within the same file to access private members

**Comment by nickdnk** [comment]
I think that solved it. Now I just have to deal with all the syntax errors I have everywhere else. Thanks :)

**Pull request merged**
