### PR TITLE
Migration to Swift 5

### PR DESCRIPTION
**Pull request by darecki**

### CODE REVIEW

**Comment by darecki** [comment]
@luispadron could you enable Swift 5 on Travis? :)

**Comment by parrotbait** [comment]
Another vote on this one - it's blocking me due to the Swift 5 compile time error

**Comment by parrotbait** [comment]
Thanks @darecki for the PR!

**Comment by luispadron** [comment]
Thanks for the PR!

I think all you have to do is change the `.travis.yml` file to use `osx_image: 10.2`, however, that version of Xcode doesn't show up [here](https://docs.travis-ci.com/user/reference/osx/) so not sure if it supports Swift 5 yet? We can go ahead and make that change to the travis file and push and it should work if they support it.

**Comment by MihaelIsaev** [comment]
While we're waiting pod update a lib may be fixed manually like this
```swift
let a = max(ring.outerRingWidth, ring.innerRingWidth)
let b = ((valueKnobStyle?.size ?? 0) / 4)
let c = (borderWidth * 2)
let offSet = a / 2 + b + c
```

**Comment by haroldogtf** [comment]
Temporary workaround
`pod 'UICircularProgressRing', :git => 'https://github.com/darecki/UICircularProgressRing.git', :branch => 'swift_5'
`

**Comment by darecki** [comment]
> Thanks for the PR!
> 
> I think all you have to do is change the `.travis.yml` file to use `osx_image: 10.2`, however, that version of Xcode doesn't show up [here](https://docs.travis-ci.com/user/reference/osx/) so not sure if it supports Swift 5 yet? We can go ahead and make that change to the travis file and push and it should work if they support it.

I just found this: https://blog.travis-ci.com/2019-02-12-xcode-10-2-beta-2-is-now-available
I assume for now it should run on Xcode 10.2-beta and then switch to full version automatically. I'll update my PR

**Comment by yusuftor** [comment]
Can we merge this now?

**Comment by darecki** [comment]
@luispadron Do you think you can merge and release a new version?

**Comment by luispadron** [comment]
Sorry, been busy with school.

Thanks for the great work, I'll merge this and get a new pod and Carthage release out ASAP.

**Comment by luispadron** [comment]
Available now in [6.1.0](https://github.com/luispadron/UICircularProgressRing/releases/tag/v6.1.0)

**Pull request merged**
