### PR TITLE
Update UICircularProgressRing.podspec for dependency

### PR DESCRIPTION
**Pull request by younatics**
Hello, I use your library in [MediaBrowser](https://github.com/younatics/MediaBrowser)

In your Podspec, there is no deployment target so I can't build travis in my libs.
Could you update for me?

Thanks!

### CODE REVIEW

**Comment by luispadron** [comment]
I don't know a ton about how Podspecs work or Travis, but would removing the platform from the podspec break anything or is  `s.ios.deployment_target = "8.0"` and `s.platform     = :ios, "8.0"` equivalent?

**Comment by younatics** [comment]
As you can see in here, https://guides.cocoapods.org/syntax/podspec.html#specification, you can use deployment target than platform. Thanks!

**Comment by luispadron** [comment]
Cool thanks for the info!

**Comment by younatics** [comment]
Thanks!

**Comment by younatics** [comment]
Could you update your version? (e.g. pod trunk push UICircularProgressRing.podspec)

**Comment by luispadron** [comment]
Updated in [version 1.7.2](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.7.2).

Thanks again for contributing.

**Comment by younatics** [comment]
Great!

**Pull request merged**
